# Generated by Django 4.2.1 on 2023-05-31 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_applicantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.applicant'),
        ),
    ]
